# Generated by Django 5.1.6 on 2025-02-19 14:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('type', models.CharField(choices=[('CANDIDATE', 'Nomzod'), ('EMPLOYEE', 'Xodim')], default='EMPLOYEE', max_length=255, verbose_name='Turi')),
                ('status', models.CharField(default='working', max_length=255, verbose_name='Holati')),
                ('fullname', models.CharField(max_length=255, verbose_name='To‘liq ismi')),
                ('gender', models.CharField(choices=[('male', 'Erkak'), ('female', 'Ayol')], max_length=10, verbose_name='Jinsi')),
                ('pinfl', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='PINFL 14 ta raqamdan iborat bo‘lishi kerak', regex='^\\d{14}$')], verbose_name='PINFL')),
                ('passport', models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(message='Passport seriyasi va raqami noto‘g‘ri formatda (AA1234567)', regex='^[A-Z]{2}\\d{7}$')], verbose_name='Passport')),
                ('address_of_residence', models.CharField(max_length=255, verbose_name='Manzili')),
                ('phone_number', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Telefon raqam +998 bilan boshlanishi va 9 ta raqamdan iborat bo‘lishi kerak', regex='^\\+?998?\\d{9}$')], verbose_name='Telefon raqami')),
                ('additional_phone', models.CharField(blank=True, max_length=13, null=True, validators=[django.core.validators.RegexValidator(message='Telefon raqam +998 bilan boshlanishi va 9 ta raqamdan iborat bo‘lishi kerak', regex='^\\+?998?\\d{9}$')], verbose_name='Qo‘shimcha telefon')),
                ('bachelor_university', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bakalavr universiteti')),
                ('bachelor_graduation_year', models.IntegerField(blank=True, null=True, verbose_name='Bakalavr tugatgan yili')),
                ('master_university', models.CharField(blank=True, max_length=255, null=True, verbose_name='Magistratura universiteti')),
                ('master_graduation_year', models.IntegerField(blank=True, null=True, verbose_name='Magistratura tugatgan yili')),
                ('academic_title_date', models.DateField(blank=True, null=True, verbose_name='Ilmiy unvon berilgan sana')),
                ('resume', models.FileField(help_text='PDF formatida', upload_to='resumes/', verbose_name='Rezyume')),
                ('hired_date', models.DateField(blank=True, null=True, verbose_name='Ishga qabul qilingan sana')),
                ('left_date', models.DateField(blank=True, null=True, verbose_name='Ishdan ketgan sana')),
                ('academic_degree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.academicdegree', verbose_name='Ilmiy daraja')),
                ('academic_specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.academicspecialization', verbose_name='Ilmiy yo‘nalish')),
                ('academic_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.academictitle', verbose_name='Ilmiy unvon')),
                ('birthplace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='birth_personnel', to='core.district', verbose_name='Tug‘ilgan joyi')),
                ('education_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.educationlevel', verbose_name='Ta’lim darajasi')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.nation', verbose_name='Millati')),
                ('place_of_residence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resident_personnel', to='core.district', verbose_name='Yashash joyi')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personnel', to='departments.position', verbose_name='Lavozimi')),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'ordering': ['fullname'],
            },
        ),
        migrations.CreateModel(
            name='PersonnelStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
                ('old_status', models.CharField(max_length=255, verbose_name='Oldingi holat')),
                ('new_status', models.CharField(max_length=255, verbose_name='Yangi holat')),
                ('reason', models.TextField(verbose_name='o‘zgartirish sababi')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='o‘zgartirgan foydalanuvchi')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='personnel.personnel', verbose_name='Xodim')),
            ],
            options={
                'verbose_name': 'Holat tarixi',
                'verbose_name_plural': 'Holat tarixlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='personnel',
            index=models.Index(fields=['type', 'status'], name='personnel_p_type_1ca2d6_idx'),
        ),
        migrations.AddIndex(
            model_name='personnel',
            index=models.Index(fields=['pinfl'], name='personnel_p_pinfl_b90a48_idx'),
        ),
        migrations.AddIndex(
            model_name='personnel',
            index=models.Index(fields=['passport'], name='personnel_p_passpor_b101c5_idx'),
        ),
    ]
