# Generated by Django 5.1.6 on 2025-02-19 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
            ],
            options={
                'verbose_name': 'Nomzod',
                'verbose_name_plural': 'Nomzodlar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('personnel.personnel',),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('personnel.personnel',),
        ),
    ]
