# Generated by Django 5.1.6 on 2025-02-19 16:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_candidate_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='birthdate',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Tug‘ilgan sanasi'),
            preserve_default=False,
        ),
    ]
