# Generated by Django 5.1.6 on 2025-02-19 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='languageproficiency',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='personnel.personnel', verbose_name='Xodim'),
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='core.region', verbose_name='Viloyat'),
        ),
        migrations.AddField(
            model_name='stateaward',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='personnel.personnel', verbose_name='Xodim'),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='personnel.personnel', verbose_name='Xodim'),
        ),
        migrations.AlterUniqueTogether(
            name='languageproficiency',
            unique_together={('language_name', 'proficiency_level')},
        ),
        migrations.AlterUniqueTogether(
            name='stateaward',
            unique_together={('personnel', 'name', 'year')},
        ),
    ]
